server: 
  port: 8000

spring:
  application:
   name: api-gateway
   
  cloud:
    gateway:
      routes:
      - id: user-service
        uri:
         lb://user-service
        predicates:
        - Path=/hello1
        
      - id: order-service
        uri:
         lb://order-service
        predicates:
        - Path=/hello2
        
      - id: supplier-inventory-service
        uri:
         lb://supplier-inventory-service
        predicates:
        - Path=/hello3