version: '3'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
  app:
    build: .
    image: app
    restart: on-failure
    ports:
       - 8090:8091
    environment: 
      spring.datasource.url: jdbc:mysql://mysqldb:3306/notesdb
      spring.datasource.username: root
      spring.datasource.password: root
      spring.datasource.platform: mysql
      MYSQL_DATABASE: notesdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    links:
      - mysqldb
    depends_on:
      - mysqldb
    
  